"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ['config.sample.xml', 'Foundation.bridgesupport', 'UNLICENSE', 'icons']
OPTIONS = {
 'iconfile': 'sync.icns',
 'packages': 'fileconveyor,boto,cloudfiles,django,storages',
 'plist': 'Info.plist'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
